FROM python:3.11

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# install uv
RUN pip install uv

# copy only dependency files first (cache optimization)
COPY pyproject.toml uv.lock* /app/

# install into SYSTEM (no venv!)
RUN uv pip install --system .

# now copy rest of code
COPY . /app/

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]