POST http://localhost:8000/users/ HTTP/1.1
Content-Type: application/json

{
    "username": "bobb",
    "email": "bobby@gmail.com",
    "password": "bob123!1"
}


###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "bobby",
    "password": "bob"
}